"use client";

import { useState } from "react";
import type { ApplicationPackage } from "@/app/lib/ai/contracts";

/* ─────────────────────────────────────────────────────────
   GeneratedPackageView — renders an automatically prepared
   ApplicationPackage as a clean application summary.

   Match summary and missing information stay always visible
   (short, critical). Longer content — tailored CV, motivation
   letter, recruiter message, application answers — sits in
   collapsible sections, open by default so nothing requires
   an extra click to inspect, but the page can be tidied up.

   Read-only + copy actions. Generation happens in the
   automation orchestrator, never here.
   ───────────────────────────────────────────────────────── */

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className="text-[11px] font-medium px-2.5 py-1 rounded-lg flex-shrink-0"
      style={{
        background: "var(--blue-dim)",
        color: copied ? "#4ade80" : "#93c5fd",
        border: `1px solid ${copied ? "rgba(34,197,94,0.25)" : "rgba(59,130,246,0.2)"}`,
      }}
      onClick={(e) => {
        e.stopPropagation();
        navigator.clipboard.writeText(text).then(() => {
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        });
      }}
    >
      {copied ? "✓ Copied" : "📋 Copy"}
    </button>
  );
}

function Section({
  title,
  icon,
  action,
  defaultOpen = true,
  children,
}: {
  title: string;
  icon: string;
  action?: React.ReactNode;
  defaultOpen?: boolean;
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="rounded-lg" style={{ background: "var(--bg-raised)", border: "1px solid var(--border-subtle)" }}>
      <div className="flex items-center justify-between gap-2 px-4 py-3">
        <button
          type="button"
          className="flex items-center gap-2 text-[12px] font-semibold flex-1 text-left"
          style={{ color: "var(--text-primary)" }}
          onClick={() => setOpen((v) => !v)}
        >
          <span className="text-[10px] flex-shrink-0" style={{ color: "var(--text-muted)" }}>{open ? "▾" : "▸"}</span>
          <span>{icon} {title}</span>
        </button>
        {action}
      </div>
      {open && <div className="px-4 pb-4">{children}</div>}
    </div>
  );
}

export default function GeneratedPackageView({
  pkg,
  isDemo,
  userProvidedAnswers = [],
}: {
  pkg: ApplicationPackage;
  isDemo: boolean;
  userProvidedAnswers?: { question: string; answer: string }[];
}) {
  return (
    <div className="dash-panel p-5 flex flex-col gap-4"
         style={{ borderColor: "rgba(99,102,241,0.25)" }}>

      {/* Header */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <p className="text-sm font-bold" style={{ color: "var(--text-primary)" }}>
          Application Package
        </p>
        {isDemo ? (
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full"
                style={{ background: "rgba(250,204,21,0.08)", color: "#fde047", border: "1px solid rgba(250,204,21,0.2)" }}>
            ⚡ Demo fallback — add GEMINI_API_KEY for real AI generation
          </span>
        ) : (
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full"
                style={{ background: "rgba(34,197,94,0.12)", color: "#4ade80", border: "1px solid rgba(34,197,94,0.2)" }}>
            ✓ Generated by Gemini AI
          </span>
        )}
      </div>

      {/* Match summary — always visible */}
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>Match Summary</p>
        <div className="flex items-center gap-4 flex-wrap mb-3">
          <div className="flex items-center gap-2">
            <span className="text-2xl font-bold gradient-text">{pkg.matchScore}%</span>
            <span className="text-[11px] font-medium px-2 py-0.5 rounded-full" style={
              pkg.decision === "Strong fit"
                ? { background: "rgba(34,197,94,0.12)", color: "#4ade80", border: "1px solid rgba(34,197,94,0.2)" }
                : pkg.decision === "Possible fit"
                ? { background: "rgba(250,204,21,0.08)", color: "#fde047", border: "1px solid rgba(250,204,21,0.2)" }
                : { background: "rgba(248,113,113,0.1)", color: "#f87171", border: "1px solid rgba(248,113,113,0.2)" }
            }>{pkg.decision}</span>
          </div>
          <p className="text-[12px] leading-relaxed flex-1 min-w-[200px]" style={{ color: "var(--text-secondary)" }}>
            {pkg.fitSummary}
          </p>
        </div>

        {/* Strengths + Gaps */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {pkg.strengths.length > 0 && (
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>Strengths</p>
              <div className="flex flex-wrap gap-1.5">
                {pkg.strengths.map((s, i) => <span key={i} className="skill-chip skill-chip--match text-[11px]">{s}</span>)}
              </div>
            </div>
          )}
          {pkg.gaps.length > 0 && (
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>Gaps</p>
              <div className="flex flex-wrap gap-1.5">
                {pkg.gaps.map((g, i) => <span key={i} className="skill-chip skill-chip--missing text-[11px]">{g}</span>)}
              </div>
            </div>
          )}
        </div>

        {pkg.risks.length > 0 && (
          <div className="mt-3">
            <p className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: "var(--text-muted)" }}>Risks</p>
            <div className="flex flex-col gap-1.5">
              {pkg.risks.map((r, i) => (
                <div key={i} className="flex items-start gap-2 text-[12px]" style={{ color: "var(--text-secondary)" }}>
                  <span className="flex-shrink-0 w-4 h-4 rounded flex items-center justify-center text-[9px] font-bold mt-0.5"
                        style={{ background: "rgba(248,113,113,0.08)", color: "#f87171", border: "1px solid rgba(248,113,113,0.15)" }}>!</span>
                  {r}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Tailored CV */}
      <Section title="Tailored CV" icon="📄">
        <p className="text-[13px] font-semibold mb-1" style={{ color: "var(--text-primary)" }}>{pkg.cvAdaptation.headline}</p>
        <p className="text-[12px] leading-relaxed mb-2" style={{ color: "var(--text-secondary)" }}>{pkg.cvAdaptation.summary}</p>
        {pkg.cvAdaptation.bulletSuggestions.length > 0 && (
          <ul className="flex flex-col gap-1 mb-2">
            {pkg.cvAdaptation.bulletSuggestions.map((b, i) => (
              <li key={i} className="text-[12px] flex items-start gap-1.5" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#a5b4fc" }}>•</span>{b}
              </li>
            ))}
          </ul>
        )}
        {pkg.cvAdaptation.keywords.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {pkg.cvAdaptation.keywords.map((k, i) => (
              <span key={i} className="text-[10px] font-medium px-2 py-0.5 rounded-md"
                    style={{ background: "rgba(99,102,241,0.08)", color: "#a5b4fc", border: "1px solid rgba(99,102,241,0.15)" }}>{k}</span>
            ))}
          </div>
        )}
      </Section>

      {/* Motivation Letter */}
      <Section title={`Motivation Letter — ${pkg.coverLetter.subject}`} icon="✉️" action={<CopyButton text={pkg.coverLetter.body} />}>
        <p className="text-[12px] leading-[1.75] whitespace-pre-line" style={{ color: "var(--text-secondary)" }}>
          {pkg.coverLetter.body}
        </p>
      </Section>

      {/* Recruiter Message */}
      {pkg.recruiterMessage && (
        <Section title="Recruiter Message" icon="💬" action={<CopyButton text={pkg.recruiterMessage} />}>
          <p className="text-[12px] leading-[1.75] whitespace-pre-line" style={{ color: "var(--text-secondary)" }}>
            {pkg.recruiterMessage}
          </p>
        </Section>
      )}

      {/* Application Answers */}
      {pkg.applicationAnswers.length > 0 && (
        <Section title="Application Answers" icon="📝">
          <div className="flex flex-col gap-2">
            {pkg.applicationAnswers.map((qa, i) => {
              const provided = userProvidedAnswers.find((a) => a.question === qa.question);
              return (
                <div key={i} className="rounded-lg p-3" style={{ background: "var(--bg-overlay)", border: "1px solid var(--border-subtle)" }}>
                  <div className="flex items-start gap-2 mb-1">
                    <span className="text-[10px] font-bold px-1.5 py-0.5 rounded flex-shrink-0"
                          style={provided
                            ? { background: "rgba(34,197,94,0.06)", color: "#4ade80", border: "1px solid rgba(34,197,94,0.15)" }
                            : qa.confidence === "needs-user-input"
                            ? { background: "rgba(248,113,113,0.08)", color: "#f87171", border: "1px solid rgba(248,113,113,0.15)" }
                            : qa.confidence === "medium"
                            ? { background: "rgba(250,204,21,0.06)", color: "#fde047", border: "1px solid rgba(250,204,21,0.15)" }
                            : { background: "rgba(34,197,94,0.06)", color: "#4ade80", border: "1px solid rgba(34,197,94,0.15)" }
                          }>
                      {provided ? "Your answer" : qa.confidence === "needs-user-input" ? "Needs input" : qa.confidence}
                    </span>
                    <p className="text-[12px] font-medium" style={{ color: "var(--text-primary)" }}>{qa.question}</p>
                  </div>
                  {provided ? (
                    <p className="text-[12px] leading-relaxed ml-1" style={{ color: "var(--text-secondary)" }}>{provided.answer}</p>
                  ) : qa.answer ? (
                    <p className="text-[12px] leading-relaxed ml-1" style={{ color: "var(--text-secondary)" }}>{qa.answer}</p>
                  ) : userProvidedAnswers.length > 0 ? (
                    <p className="text-[12px] italic ml-1" style={{ color: "var(--text-muted)" }}>No AI answer — see your provided answers below.</p>
                  ) : (
                    <p className="text-[12px] italic ml-1" style={{ color: "#f87171" }}>No answer — requires your input before applying.</p>
                  )}
                </div>
              );
            })}
          </div>

          {userProvidedAnswers.filter((a) => !pkg.applicationAnswers.some((qa) => qa.question === a.question)).length > 0 && (
            <div className="flex flex-col gap-2 mt-3 pt-3" style={{ borderTop: "1px solid var(--border-subtle)" }}>
              <p className="text-[10px] font-semibold uppercase tracking-wider" style={{ color: "var(--text-muted)" }}>Your Provided Answers</p>
              {userProvidedAnswers
                .filter((a) => !pkg.applicationAnswers.some((qa) => qa.question === a.question))
                .map((a, i) => (
                  <div key={i} className="rounded-lg p-3" style={{ background: "var(--bg-overlay)", border: "1px solid var(--border-subtle)" }}>
                    <p className="text-[12px] font-medium mb-0.5" style={{ color: "var(--text-primary)" }}>{a.question}</p>
                    <p className="text-[12px]" style={{ color: "var(--text-secondary)" }}>{a.answer}</p>
                  </div>
                ))}
            </div>
          )}
        </Section>
      )}

      {/* Missing information — always visible when present */}
      {pkg.missingInformation.length > 0 && (
        <div className="rounded-lg px-4 py-3" style={{ background: "rgba(251,146,60,0.04)", border: "1px solid rgba(251,146,60,0.15)" }}>
          <p className="text-[10px] font-semibold uppercase tracking-wider mb-2" style={{ color: "#fb923c" }}>Missing Information</p>
          <ul className="flex flex-col gap-1">
            {pkg.missingInformation.map((item, i) => (
              <li key={i} className="text-[12px] flex items-start gap-1.5" style={{ color: "var(--text-secondary)" }}>
                <span style={{ color: "#fb923c" }}>○</span>{item}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Recommended next step */}
      {pkg.recommendedNextStep && (
        <div className="rounded-lg px-4 py-2.5 text-[12px]"
             style={{ background: "rgba(59,130,246,0.04)", border: "1px solid var(--border-subtle)", color: "var(--text-secondary)" }}>
          💡 <span className="font-semibold" style={{ color: "var(--text-primary)" }}>Recommended next step: </span>
          {pkg.recommendedNextStep}
        </div>
      )}

      <p className="text-[11px]" style={{ color: "var(--text-muted)" }}>
        🔒 Nothing has been submitted externally.
      </p>
    </div>
  );
}
